config/routes.rb
ThermicWhims::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root :to => 'home#index'

  resources :videos
  resources :memes
  resources :fountains
  resources :works
  resources :tags

end

app/models/fountain.rb
class Fountain < ActiveRecord::Base

	acts_as_taggable

	has_and_belongs_to_many :videos
	has_and_belongs_to_many :memes
	has_and_belongs_to_many :tags
	has_and_belongs_to_many :works

	attr_accessible :tag_list, :video_ids, :meme_ids, :work_ids, :tag_ids, :name, :department,
					:pic_url, :homepage_url, :dates


  rails_admin do 
    list do 
      field :name
      field :department
    end

    edit do
      field :name
      field :department
      field :pic_url
      field :homepage_url
      field :dates do
      	label "Lifespan"
      end
      field :tag_list do
      	label "Tags"
        html_attributes do
          {:style => "width:90%"}
        end
      end
    end
  end
end

app/models/meme.rb
class Meme < ActiveRecord::Base

	acts_as_taggable

	validates_presence_of :fountain_ids, :text

	has_and_belongs_to_many :fountains
	has_and_belongs_to_many :videos

	attr_accessible :tag_list, :tag_ids, :fountain_ids, :fountains, :video_ids, :text, :source_url

	def fountains_enum
		all_fountains = {}
		Fountain.all.each do |f|
			all_fountains[f.id] = f
		end
		all_fountains.map{|key, val| [val.name, key]}
	end


  rails_admin do 
    list do 
      field :text
      field :tag_list
      field :fountains
    end

    edit do
      field :text
      field :source_url
      field :fountain_ids, :enum do
      	label "Fountain"
      	enum_method do 
      	  :fountains_enum
      	end
      end
      field :tag_list do
      	label "Tags"
        html_attributes do
          {:style => "width:90%"}
        end
      end
    end
  end
end

app/models/tag.rb
class Tag < ActsAsTaggableOn::Tag
end

app/models/tagging.rb
class Tagging < ActsAsTaggableOn::Tagging
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :meme_comment_ids, :video_comment_ids, :email, :password, :password_confirmation
end

app/models/video.rb
class Video < ActiveRecord::Base

	acts_as_taggable

	has_and_belongs_to_many :fountains
	has_and_belongs_to_many :memes

	attr_accessible :tag_list, :fountain_ids, :meme_ids, :url, :title

	def construct_embed_url
		#eventually I want custom styling, this code removes youtube default
		#for now commented out so people know what videos are
		"http://" + self.url # + "?hd=1&rel=0&autohide=1&showinfo=0"
	end

	def fountains_enum
		all_fountains = {}
		Fountain.all.each_with_index do |f, i|
			all_fountains[i+1] = f
		end
		all_fountains.map{|key, val| [val.name, key]}
	end

  rails_admin do 
    list do 
      field :title
      field :url
    end

    edit do
      field :title
      field :url
      field :fountain_ids, :enum do
      	label "Fountain"
      	enum_method do 
      	  :fountains_enum
      	end
      end
      field :tag_list do
      	label "Tags"
        html_attributes do
          {:style => "width:90%"}
        end
      end
    end
  end
end

app/models/work.rb
class Work < ActiveRecord::Base

	acts_as_taggable

	has_and_belongs_to_many :fountains

	attr_accessible :tag_list, :fountain_ids, :full_text, :title, :link


  rails_admin do 
    list do 
      field :title
      field :link
    end

    edit do
      field :title
      field :link
      field :full_text
      field :tag_list do
      	label "Tags"
        html_attributes do
          {:style => "width:90%"}
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/fountains_controller.rb
class FountainsController < ApplicationController

	def index
		@fountains = Fountain.paginate(:page => params[:page], :per_page => 12)
	end

	def show
		@fountain = Fountain.find(params[:id])
	end

private
	def fountain_params
		params.require(:fountain).permit(:id)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@videos = Video.all
		@memes = Meme.all
	end
end

app/controllers/memes_controller.rb
class MemesController < ApplicationController

	def index
		@memes = Meme.paginate(:page => params[:page], :per_page => 12)
	end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	def index
		@tags = ActsAsTaggableOn::Tag.all
	end

	def show
		@tag = ActsAsTaggableOn::Tag.find(params[:id])
		memes_with_tag = []
		Meme.all.each do |meme|
			if meme.tag_list.include?(@tag.name)
				memes_with_tag << meme
			end
		end
		@memes = memes_with_tag		

		videos_with_tag = []
		Video.all.each do |video|
			if video.tag_list.include?(@tag.name)
				videos_with_tag << video
			end
		end
		@videos = videos_with_tag		

		works_with_tag = []
		Work.all.each do |work|
			if work.tag_list.include?(@tag.name)
				works_with_tag << work
			end
		end
		@works = works_with_tag
	end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

	def index
		@videos = Video.paginate(:page => params[:page], :per_page => 12)
	end

	def show
		@video = Video.find(params[:id])
	end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/fountains/index.html.erb
<div id="fountain-page">
	<h1 class="index-title">Fountains</h1>
	<ul class="fountains">
		<% @fountains.each do |fountain| %>
			<%= link_to(fountain) do %>
			<li class="fountain"%><span class="fountain-image"><%= image_tag fountain.pic_url %></span><span class="fountain-name"></span><%= fountain.name %><span class="department">~ <%= fountain.department %></span></li>
			<% end %>
		<% end %>
	</ul>

	<%= will_paginate @fountains %>

</div>

app/views/fountains/show.html.erb
	<h1 class="index-title"><%= @fountain.name %></h1>
<%= image_tag @fountain.pic_url %>
<% @fountain.memes.each do |meme| %>
	<li class="meme" %><%= meme.text %><span class="signature">~ <%= meme.fountains.first.name %></span></li>
<% end %> 

app/views/home/index.html.erb
<div id="home-page">

	<ul class="videos">
		<% if @videos.count > 3 %>
			<% videos = @videos.shuffle %> 
			<% 4.times do |i| %>
				<% video = videos.delete_at(0) %>
				<li id="<%= i %>" class=<%= i.odd? ? "nudge-video-left" : "" %> ><iframe width="480" height="315" src="<%= video.construct_embed_url %>" frameborder="0" allowfullscreen></iframe></li>
			<% end %>
		<% end %>
	</ul>

	<ul class="memes">
		<% if @memes.count > 5 %>
			<% memes = @memes.shuffle %> 
			<% 6.times do |i| %>
				<% meme = memes.delete_at(0) %>
				<li class="meme"%>
					<span class="meme-text"><%= meme.text %></span>
					<span class="signature">~ <%= link_to meme.fountains.first.name, fountain_path(meme.fountains.first) %></span></br>					
					<span class="meme-tags">
					<% if meme.tags.count > 0 %>
						<strong>Tags: </strong> <% meme.tags.each do |tag| %>
							<%= link_to tag.name, tag_path(tag) %> 
						<% end %></span>
					<% end %>
				</li>
			<% end %>
		<% end %>
	</ul>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thermic Whims | Meme Trading for the Intellectually Curious</title>

  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag 'base.css', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header>

		<p id="schrodinger" class="meme">There are... organisms so small that they are strongly affected by... the thermic whims of the surrounding medium; they have no choice.  If they had some locomotion of their own they might nevertheless succeed in getting from one place to another-- but with some difficulty... like a small boat in a rough sea.
		<span class="signature">~ Erwin Schrodinger</span></p>

		<%= link_to image_tag("logo.jpg", id: "logo"), root_path %>
		
		<% @meme = Meme.first(:order => "RANDOM()") %>

		<p id="header-meme" class="meme"><%= @meme.text %><span class="signature">~ <%= link_to @meme.fountains.first.name, fountain_path(@meme.fountains.first) %></span></p>

		<ul class="nav">
		  <li><%= link_to "Home", root_path %></li>
		  <li><%= link_to "Memes", memes_path %></li>
		  <li><%= link_to "Fountains", fountains_path %></li>
		  <li><%= link_to "Videos", videos_path %></li>
		  <li><%= link_to "Works", works_path %></li>
		  <%= render 'devise/menu/registration_items' %>
		  <%= render 'devise/menu/login_items' %>
		</ul>

		   <p class="notice"><%= notice %></p>
		   <p class="alert"><%= alert %></p>

	</header>

	<article>

<%= yield %>

	</article>

	<footer>
		<p> <%= "\u00A9" + Time.now.year.to_s %> Harland Hauger</p>
	</footer>

</body>
</html>

app/views/memes/index.html.erb
<div id="meme-page">
	<h1 class="index-title">Memes</h1>
	<ul class="memes">
		<% @memes.each do |meme| %>
			<li class="meme"%>
				<span class="meme-text"><%= meme.text %></span>
				<span class="signature">~ <%= link_to meme.fountains.first.name, fountain_path(meme.fountains.first) %></span></br>
				<span class="meme-tags">
				<% if meme.tags.count > 0 %>
					<strong>Tags: </strong> <% meme.tags.each do |tag| %>
						<%= link_to tag.name, tag_path(tag) %> 
					<% end %></span>
				<% end %>
			</li>
		<% end %>
	</ul>

	<%= will_paginate @memes %>

</div>

app/views/tags/show.html.erb
<div class="tag-page">
	<h1 class="index-title"><%= @tag.name %></h1>

	<% @videos.each do |video| %>
		<div class="tagged-videos" %><iframe height="240px" width="360px" src="<%= video.construct_embed_url %>" frameborder="0" allowfullscreen></iframe></div>
	<% end %>

	<% @works.each do |work| %>
		<%= link_to work.name, work_path(work) %>
	<% end %>

	<% @memes.each do |meme| %>
		<li class="meme"%>
			<span class="meme-text"><%= meme.text %></span>
			<span class="signature">~ <%= link_to meme.fountains.first.name, fountain_path(meme.fountains.first) %></span></br>	
	<% end %>
</div>

app/views/videos/index.html.erb
<div id="video-page">
	<h1 class="index-title">Videos</h1>

	<ul class="videos">
		<% @videos.each do |video| %>
			<li> <span class="video-title"><%= link_to video.title, video_path(video) %></span>
			<% if video.fountains.count > 0 %>
				</br><strong>Fountains:</strong><% video.fountains.each do |fountain| %>
						<%= link_to fountain.name, fountain_path(fountain) %>
					<% end %>
			<% end %>
			<% if video.tags.count > 0 %>
				</br><strong>Tags: </strong> <% video.tags.each do |tag| %>
					<%= link_to tag.name, tag_path(tag) %> 
				<% end %>
			<% end %></li>
		<% end %>
	</ul>

	<%= will_paginate @videos %>

</div>

app/views/videos/show.html.erb
<div id="video-page">

	<div class="video-show" %><iframe height="480px" src="<%= @video.construct_embed_url %>" frameborder="0" allowfullscreen></iframe></div>

	<div class="height-spacer"></div>

</div>

app/views/works/index.html.erb
<div id="works-page">
	<h1 class="index-title">Works</h1>
</div>